package com.twilight.eCommercePlatform.enums;

public enum AuthWork {
    CREATE_ORDER,DELETE_ORDER,CANCEL_ORDER,UPDATE_ORDER,
    CREATE_USER,DELETE_USER,UPDATE_USER,
    CREATE_PRODUCT,UPDATE_PRODUCT,DELETE_PRODUCT,
    CREATE_RESTAURANT,UPDATE_RESTAURANT,DELETE_RESTAURANT
}
