spring.application.name=ecommerce-platform


# ===============================
# MySQL Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/twilightdb?useSSL=false&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=Debasis@2004MYSQL

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ================================
# RazorPay Key
# ================================
razorpay.key_id=rzp_test_RxA0uhA3RNsHy2
razorpay.key_secret=5Vy3gKhDLAHnxQCP3IN8pngI

