spring.application.name=ecommerec-platform
spring.datasource.url=jdbc:postgresql://twilight.c3m86iikejsk.eu-north-1.rds.amazonaws.com:5432/twilightdb
spring.datasource.username=teamuser
spring.datasource.password=twilight.org2025
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect